services:
  - type: web
    name: stock-predictor-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FINNHUB_API_KEY
        sync: false
    autoDeploy: true 